### PR TITLE
[We Can Merge]Soloving travis build error

### PR DESCRIPTION
**Pull request by allenzhong**
Don't Merge it. I'm trying solve.

### CODE REVIEW

**Comment by allenzhong** [comment]
@chandleryang76 @JohnnyJ0622 I solved yesterday's problem.

**Comment by allenzhong** [comment]
@chandleryang76  @JohnnyJ0622 Rright Now, I need merge this branch into `Sprint1`. And rebase `Sprint1` to `BasicSearch`, which could make `BasicSearch` branch pass `travis-ci`.

**Review by JohnnyJ0622 — APPROVED** [review]
It's ok.

**Comment by chandleryang76** [comment]
Cool

**Pull request merged**
