### PR TITLE
Fixed the issue of Rspec testing caused by database changes.

### PR DESCRIPTION
**Pull request by JohnnyJ0622**
Please check it, thanks.

### CODE REVIEW

**Comment by allenzhong** [comment]
rspec tests passed, cucumber not yet.

**Comment by JohnnyJ0622** [comment]
I'd like to create another branch to fix issue of cucumber, is it ok?

**Comment by allenzhong** [comment]
it is better to do this in this branch, because we have to make sure ci passed.

**Comment by JohnnyJ0622** [comment]
Sure.

**Pull request closed without merging**
