### PR TITLE
Coffee

### PR DESCRIPTION
**Pull request by Isabella930514**
I try to write the step_definition of user story 8. Please check it. If it is wrong, please tell me and I can change it.

### CODE REVIEW

**Comment by allenzhong** [comment]
What's Coffee?

**Comment by Isabella930514** [comment]
My branch name

2016年10月5日星期三，Allen Zhong notifications@github.com 写道：

**Comment by allenzhong** [comment]
@Isabella930514 but there is no any meaning relate to what you did or you are doing.

**Comment by Isabella930514** [comment]
Should I change it ？

2016年10月5日星期三，Allen Zhong notifications@github.com 写道：

**Comment by allenzhong** [comment]
@Isabella930514 And please don't merge any branch before testing passed.

**Comment by allenzhong** [comment]
@Isabella930514 you have to change it to some words that could help people know what you did

**Comment by Isabella930514** [comment]
👌，I got it

2016年10月5日星期三，Allen Zhong notifications@github.com 写道：

**Comment by allenzhong** [comment]
@Isabella930514 Next time, don't create Push Request. Just push from your local repo. Once remote branch created, others can pull it to their local machine and keep working on it.

**Comment by allenzhong** [comment]
@Isabella930514 Creating a `Push Request` means the work is done and just need other people review, and then merge into main branch. make sense?

**Pull request closed without merging**
