### PR TITLE
Select column

### PR DESCRIPTION
**Pull request by allenzhong**
- columns can be selected to show or hide

### CODE REVIEW

**Comment by chandleryang76** [comment]
It's Okay

**Review by JohnnyJ0622 — APPROVED** [review]
These work are ready for merging, thanks a lot.

**Review by JohnnyJ0622 — COMMENTED** [review]
The title can be hided, but the result cannot do it.

**Review by JohnnyJ0622 — COMMENTED** [review]
The title can be hided, but the result cannot do it.

**Review by JohnnyJ0622 — APPROVED** [review]
It could be merged.

**Pull request merged**
