### PR TITLE
Export pdf

### PR DESCRIPTION
**Pull request by allenzhong**
- Result table is able to be exported to PDF

### CODE REVIEW

**Comment by Isabella930514** [comment]
Ok

**Comment by chandleryang76** [comment]
It's okay

**Review by Isabella930514 — COMMENTED** [review]
Look nice

**Review by Isabella930514 — COMMENTED** [review]
Looks good

**Review by Isabella930514 — COMMENTED** [review]
Ok

**Review by JohnnyJ0622 — APPROVED** [review]
These can be merged, thx.

**Comment by allenzhong** [comment]
@chandleryang76 @JohnnyJ0622 @Isabella930514 
All passed

**Comment by allenzhong** [comment]
:sunglasses: :laughing: Hahahaha, it's done.

**Comment by JohnnyJ0622** [comment]
Cool

**Comment by Isabella930514** [comment]
These are perfect

**Pull request merged**
