### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by chandleryang76**
- Use environment value to share between teams
- 2 heroku app : one is only for master branch , another is for Sprint branches

### CODE REVIEW

**Comment by allenzhong** [comment]
I just check environment variables, are they correct? Could you give us Heroku Url to visit our website?

If it is correct, you can merge. Cheers.

**Comment by chandleryang76** [comment]
for master - https://sdm2016friends.herokuapp.com/ 
for sprint - https://sprintfortest.herokuapp.com

**Comment by allenzhong** [comment]
@chandleryang76 I also forgot testing in this branch, could I add testing in .travis.yml directly?

**Comment by chandleryang76** [comment]
sure, As you wish

**Pull request merged**
